controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_weather:
    path: /weather/weather
    controller: App\Controller\WeatherController::weather
